Document: stolon
Title: Debian stolon Manual
Author: <insert document author here>
Abstract: This manual describes what stolon is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/stolon/stolon.sgml.gz

Format: postscript
Files: /usr/share/doc/stolon/stolon.ps.gz

Format: text
Files: /usr/share/doc/stolon/stolon.text.gz

Format: HTML
Index: /usr/share/doc/stolon/html/index.html
Files: /usr/share/doc/stolon/html/*.html
